
//List of simple testing commands

GET http://localhost:3000/events

#####

POST http://localhost:3000/events
Content-Type: application/json

 {
    "name": "Hiking",
    "id": 12186,
    "adminId": 16,
    "attendanceCode": "randomString",
    "pointReward": 300
 }

####

 GET http://localhost:3000/signup

####

POST http://localhost:3000/signup
Content-Type: application/json

{
    "userId": 1,
    "eventId": 12186
}

####

GET http://localhost:3000/attendance
Content-Type: application/json

{
    "userId": 2,
    "eventId": 12188,
    "attendanceCode": "randomString"
}

####

POST http://localhost:3000/events/deletion
Content-Type: application/json

{
    "eventId": 12186
}

####
POST http://localhost:3000/dummy

####

POST http://localhost:3000/user
Content-Type: application/json

{
    "id": 4,
    "points": 1000
}

####

GET http://localhost:3000/user

{
  "data": [
    {
      "userid": "256af3e4-5457-4f14-8ef4-a6c7ab93b3d6",
      "namefirst": "John",
      "namelast": "Doe",
      "username": "johndoe",
      "accesstoken": "pass123",
      "address": "123 Main St",
      "email": "john.doe@example.com",
      "points": 100,
      "followers": 15
    },
    {
      "userid": "7720ef55-48b7-47b5-a131-dcc9d4a2147b",
      "namefirst": "Jane",
      "namelast": "Smith",
      "username": "janesmith",
      "accesstoken": "password",
      "address": "456 Elm St",
      "email": "jane.smith@example.com",
      "points": 150,
      "followers": 20
    }
  ]
}



####

GET http://localhost:3000/user/userName

eg:  http://localhost:3000/user/janesmith

[
  {
    "userid": "7720ef55-48b7-47b5-a131-dcc9d4a2147b",
    "namefirst": "Jane",
    "namelast": "Smith",
    "username": "janesmith",
    "accesstoken": "password",
    "address": "456 Elm St",
    "email": "jane.smith@example.com",
    "points": 150,
    "followers": 20
  }
]







####

POST http://localhost:3000/reward
Content-Type: application/json

{
    "name": "10% off T-Shirts",
    "id": 146,
    "cost": 30
}

####

GET http://localhost:3000/reward

####

POST http://localhost:3000/redeem
Content-Type: application/json

{
    "rewardId": 146,
    "userId": 2
}



